### ISSUE TITLE
Wrong No of Arguments

### ISSUE THREAD

**Issue by JeanMathew2** [favu100/b2program#2]
# Java
./gradlew run -Planguage="java" -Pbig_integer="true/false" [-Pminint="minint" -Pmaxint="maxint"] -Pdeferred_set_size="size" -Pfile="<path_relative_to_project_directory>"

--Build is sucessful but getting wrong no of arguments. Can you pls update on this?

**Comment by favu100** [comment]
This should be fixed now, can you check this please?

**Comment by JeanMathew2** [comment]
Task :run FAILED
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
        at de.hhu.stups.codegenerator.CodeGenerator.main(CodeGenerator.java:67)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\jdk-14.0.2\bin\java.exe'' finished with non-zero exit value 1

Do we have to pass some value for "addition" arg?

**Comment by favu100** [comment]
I had some uncommited changes. Should be fixed now

**Comment by JeanMathew2** [comment]
> Task :run FAILED
Exception in thread "main" java.lang.RuntimeException: Machine Lift must have the same name as its file
        at de.prob.parser.antlr.Antlr4BParser.checkMachineName(Antlr4BParser.java:74)
        at de.prob.parser.antlr.Antlr4BParser.createBProjectFromMainMachineFile(Antlr4BParser.java:84)
        at de.prob.parser.antlr.Antlr4BParser.createBProjectFromMainMachineFile(Antlr4BParser.java:115)
        at de.hhu.stups.codegenerator.CodeGenerator.parseProject(CodeGenerator.java:223)
        at de.hhu.stups.codegenerator.CodeGenerator.generate(CodeGenerator.java:161)
        at de.hhu.stups.codegenerator.CodeGenerator.main(CodeGenerator.java:69)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\jdk-14.0.2\bin\java.exe'' finished with non-zero exit value 1


cmd : ./gradlew run -Planguage="java" -Pbig_integer="false" -Pminint="-2047" -Pmaxint="2048" -Pdeferred_set_size="10" -PuseConstraintSolving="false" -PforModelchecking="false" -Pfile="\benchmarks\ProB\Lift.mch"

**Comment by favu100** [comment]
Does it work now?

**Comment by JeanMathew2** [comment]
same error. Any other place where we need to use File.separator?

**Comment by favu100** [comment]
I have replaced "/" by File.separator in MachineReferenceGenerator. There are also some changes in ANTLR B Parser

**Comment by favu100** [comment]
Maybe B2Program does not take the latest update of the ANTLR B Parser? You can try to invoke ./gradlew eclipse --refresh-dependencies

**Comment by JeanMathew2** [comment]
Build successful for eclipse refresh

Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected in
ternal error near index 1
\
        at java.base/java.util.regex.Pattern.error(Pattern.java:2029)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1790)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1431)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1070)
        at java.base/java.lang.String.split(String.java:2353)
        at java.base/java.lang.String.split(String.java:2400)
        at de.prob.parser.antlr.Antlr4BParser.checkMachineName(Antlr4BParser.jav
a:71)
        at de.prob.parser.antlr.Antlr4BParser.createBProjectFromMainMachineFile(
Antlr4BParser.java:84)
        at de.prob.parser.antlr.Antlr4BParser.createBProjectFromMainMachineFile(
Antlr4BParser.java:115)
        at de.hhu.stups.codegenerator.CodeGenerator.parseProject(CodeGenerator.j
ava:172)
        at de.hhu.stups.codegenerator.CodeGenerator.generate(CodeGenerator.java:
126)
        at de.hhu.stups.codegenerator.CodeGenerator.main(CodeGenerator.java:61)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-14.0.2\bin\java.exe'' finished wit
h non-zero exit value 1

**Comment by favu100** [comment]
Okay, I have quoted the File.separator. Does it work now?

**Comment by JeanMathew2** [comment]
Same error still!

**Comment by JeanMathew2** [comment]
Arguments for ANTLR B Parser is wrong
Use java -jar antlr-parser-VERSION.jar FILE [TypeCheck]
 where FILE is the B file to parse and TypeCheck is true or false

after antlr update

**Comment by JeanMathew2** [comment]
build successful. Thanks a ton.
