### ISSUE TITLE
The relation operator <-> is not supported

### ISSUE THREAD

**Issue by leuschel** [favu100/b2program#3]
I get this message when using a model with <->:

Exception in thread "main" java.lang.RuntimeException: Given operator is not implemented: SET_RELATION
	at de.hhu.stups.codegenerator.generators.ExpressionGenerator.generateExpression(ExpressionGenerator.java:349)
	at de.hhu.stups.codegenerator.generators.ExpressionGenerator.visitExprOperatorNode(ExpressionGenerator.java:239)

**Comment by favu100** [comment]
This issue is solved now
